export const OpcionesEPS = [
  'ASMET SALUD EPS SAS',
  'COOSALUD ENTIDAD PROMOTORA DE SALUS SA',
  'ENTIDAD PROMOTORA DE SALUD FAMISANAR SAS',
  'ENTIDAD PROMOTORA DE SALUD SANITAS SAS',
  'EPS SURAMERICANA SA',
  'FONDO DE PRESTACIONES SOCIALES DEL MAGISTERIO',
  'FUNDACION SALUD MIA EPS',
  'NUEVA EMPRESA PROMOTORA DE SALUD SA',
  'SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REGIMEN CONTRIBUTIVO Y EL REGIMEN SU'
];

export const OpcionesRegimen = ['Contributivo', 'Subsidiado', 'Especial', 'PPNA'];